//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMCPipedGasLineAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMCPipedGasLineAPI.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This area name is already taken. Please try another..
        /// </summary>
        internal static string AreaAlreadyExist {
            get {
                return ResourceManager.GetString("AreaAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Area Name.
        /// </summary>
        internal static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The area has been inactivated..
        /// </summary>
        internal static string AresInactive {
            get {
                return ResourceManager.GetString("AresInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Bank name is already taken. Please try another..
        /// </summary>
        internal static string BankExist {
            get {
                return ResourceManager.GetString("BankExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter City Name.
        /// </summary>
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This company name is already taken. Please try another..
        /// </summary>
        internal static string CompanyAlreadyExist {
            get {
                return ResourceManager.GetString("CompanyAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company has been inactivated..
        /// </summary>
        internal static string CompanyInactive {
            get {
                return ResourceManager.GetString("CompanyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear @Fname,&lt;br/&gt;&lt;br/&gt; Your account has been created on NMC Gas PipLine. &lt;br/&gt;&lt;br/&gt;Your CustomerId : @CustomerNumber . &lt;br/&gt; Password : @password  &lt;br/&gt;&lt;br/&gt;
        ///You can pay bill online using CustomerId on below website link https://nmcadmin.azurewebsites.net/payment/login &lt;br/&gt;
        ///&lt;br/&gt;Thank You &lt;br/&gt; NMC Team.
        /// </summary>
        internal static string CustomerEmail {
            get {
                return ResourceManager.GetString("CustomerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer data imported successfully..
        /// </summary>
        internal static string CustomerImported {
            get {
                return ResourceManager.GetString("CustomerImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear @Fname,@n Your account has been created on NMC Gas PipLine.  @n Your CustomerId : @CustomerNumber . Password : @password  @n
        ///You can pay bill online using below website link  @n https://nmcadmin.azurewebsites.net/payment/login @n
        ///Thank You @n  NMC Team.
        /// </summary>
        internal static string CustomerSms {
            get {
                return ResourceManager.GetString("CustomerSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found..
        /// </summary>
        internal static string DataNotExist {
            get {
                return ResourceManager.GetString("DataNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee has been inactivated. Please contact with administrator..
        /// </summary>
        internal static string Deactivatedbyadmin {
            get {
                return ResourceManager.GetString("Deactivatedbyadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Society data deleted successfully..
        /// </summary>
        internal static string DeleteSociety {
            get {
                return ResourceManager.GetString("DeleteSociety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an Email Id.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Id is not registered with us. Please try again..
        /// </summary>
        internal static string EmailIdNotRegister {
            get {
                return ResourceManager.GetString("EmailIdNotRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Email Id or Username..
        /// </summary>
        internal static string EmailUsername {
            get {
                return ResourceManager.GetString("EmailUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee has been inactivated..
        /// </summary>
        internal static string EmployeeInactive {
            get {
                return ResourceManager.GetString("EmployeeInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found..
        /// </summary>
        internal static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload files in .xls and .xlsx format..
        /// </summary>
        internal static string FileFormate {
            get {
                return ResourceManager.GetString("FileFormate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear @Fname ,
        ///&lt;br /&gt;
        ///A request has been received to reset your password on NMC App. If you did not make any change-password request, please ignore this mail, and make sure you secure your account by changing your password any time soon.
        ///&lt;br /&gt;
        ///To reset you Password, please click on the link below...
        ///&lt;br /&gt;
        ///@callbackUrl
        ///&lt;br /&gt;
        ///Best Wishes,&lt;br /&gt;
        ///Thank You NMC Team
        ///
        ///&lt;br /&gt;  &lt;br /&gt;  
        ///You received this email because you are registered on NMC App with the email address: @NMCEmail .
        /// </summary>
        internal static string ForgotEmail {
            get {
                return ResourceManager.GetString("ForgotEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The godown has been inactivated..
        /// </summary>
        internal static string GoDownInactive {
            get {
                return ResourceManager.GetString("GoDownInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Godown Name.
        /// </summary>
        internal static string GodownName {
            get {
                return ResourceManager.GetString("GodownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot uploded image..
        /// </summary>
        internal static string ImageUploadError {
            get {
                return ResourceManager.GetString("ImageUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password. Please try again..
        /// </summary>
        internal static string InVaildUser {
            get {
                return ResourceManager.GetString("InVaildUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid credentials..
        /// </summary>
        internal static string InvalidCredential {
            get {
                return ResourceManager.GetString("InvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid OTP..
        /// </summary>
        internal static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Id . Please try again..
        /// </summary>
        internal static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password. Please try again..
        /// </summary>
        internal static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found..
        /// </summary>
        internal static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello @EmailId 
        ///&lt;br /&gt; &lt;br /&gt; Thank you for registering in NMC gas pipeline. Your One time Verification code is : @OTP   &lt;br /&gt; &lt;br /&gt; Thank you NMC Team.
        /// </summary>
        internal static string OTPEmail {
            get {
                return ResourceManager.GetString("OTPEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An message has been sent with an OTP to your registered mobile number..
        /// </summary>
        internal static string OTPRecieved {
            get {
                return ResourceManager.GetString("OTPRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must have at least one non letter or digit character. Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;). Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;)..
        /// </summary>
        internal static string PasswordValid {
            get {
                return ResourceManager.GetString("PasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment data imported successfully..
        /// </summary>
        internal static string PaymentImported {
            get {
                return ResourceManager.GetString("PaymentImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid phone number.
        /// </summary>
        internal static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For demo purposes the current provider code is:.
        /// </summary>
        internal static string ProviderCode {
            get {
                return ResourceManager.GetString("ProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello   @Name   &lt;br /&gt;  &lt;br /&gt; Please reset your password by using this given link : &lt;a href=&quot;@url&quot; &gt;Click here&lt;/a&gt; &lt;br/&gt; &lt;br/&gt; Thank You. &lt;br/&gt; NMC Team.
        /// </summary>
        internal static string ResetEmail {
            get {
                return ResourceManager.GetString("ResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password has been sent to the registered Email Id..
        /// </summary>
        internal static string Resetlink {
            get {
                return ResourceManager.GetString("Resetlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Id is not registered with us. Please try again..
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully..
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we are currently unable to service your request. Please try after some time..
        /// </summary>
        internal static string Somethingfailed {
            get {
                return ResourceManager.GetString("Somethingfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter State Name.
        /// </summary>
        internal static string StateName {
            get {
                return ResourceManager.GetString("StateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Stock Item.
        /// </summary>
        internal static string StockItem {
            get {
                return ResourceManager.GetString("StockItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stock item has been inactivated..
        /// </summary>
        internal static string StockItemInactive {
            get {
                return ResourceManager.GetString("StockItemInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email updated successfully..
        /// </summary>
        internal static string UpdateEmail {
            get {
                return ResourceManager.GetString("UpdateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data updated successfully..
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
